// Code generated by go-swagger; DO NOT EDIT.

package city

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetCitiesIDHandlerFunc turns a function with the right signature into a get cities ID handler
type GetCitiesIDHandlerFunc func(GetCitiesIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCitiesIDHandlerFunc) Handle(params GetCitiesIDParams) middleware.Responder {
	return fn(params)
}

// GetCitiesIDHandler interface for that can handle valid get cities ID params
type GetCitiesIDHandler interface {
	Handle(GetCitiesIDParams) middleware.Responder
}

// NewGetCitiesID creates a new http.Handler for the get cities ID operation
func NewGetCitiesID(ctx *middleware.Context, handler GetCitiesIDHandler) *GetCitiesID {
	return &GetCitiesID{Context: ctx, Handler: handler}
}

/*GetCitiesID swagger:route GET /cities/{id} City getCitiesId

Show a single city by id

Show a single city by id

*/
type GetCitiesID struct {
	Context *middleware.Context
	Handler GetCitiesIDHandler
}

func (o *GetCitiesID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetCitiesIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
