// Code generated by go-swagger; DO NOT EDIT.

package city

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetCitiesIDOKCode is the HTTP code returned for type GetCitiesIDOK
const GetCitiesIDOKCode int = 200

/*GetCitiesIDOK Return a single object with city data

swagger:response getCitiesIdOK
*/
type GetCitiesIDOK struct {

	/*
	  In: Body
	*/
	Payload *GetCitiesIDOKBody `json:"body,omitempty"`
}

// NewGetCitiesIDOK creates GetCitiesIDOK with default headers values
func NewGetCitiesIDOK() *GetCitiesIDOK {

	return &GetCitiesIDOK{}
}

// WithPayload adds the payload to the get cities Id o k response
func (o *GetCitiesIDOK) WithPayload(payload *GetCitiesIDOKBody) *GetCitiesIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get cities Id o k response
func (o *GetCitiesIDOK) SetPayload(payload *GetCitiesIDOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCitiesIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCitiesIDNotFoundCode is the HTTP code returned for type GetCitiesIDNotFound
const GetCitiesIDNotFoundCode int = 404

/*GetCitiesIDNotFound City not found

swagger:response getCitiesIdNotFound
*/
type GetCitiesIDNotFound struct {
}

// NewGetCitiesIDNotFound creates GetCitiesIDNotFound with default headers values
func NewGetCitiesIDNotFound() *GetCitiesIDNotFound {

	return &GetCitiesIDNotFound{}
}

// WriteResponse to the client
func (o *GetCitiesIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
