// Code generated by go-swagger; DO NOT EDIT.

package city

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/swag"
)

// GetCitiesURL generates an URL for the get cities operation
type GetCitiesURL struct {
	HasWeather *string
	Lat        *float64
	Lon        *float64

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetCitiesURL) WithBasePath(bp string) *GetCitiesURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetCitiesURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetCitiesURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/cities"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/v1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var hasWeatherQ string
	if o.HasWeather != nil {
		hasWeatherQ = *o.HasWeather
	}
	if hasWeatherQ != "" {
		qs.Set("hasWeather", hasWeatherQ)
	}

	var latQ string
	if o.Lat != nil {
		latQ = swag.FormatFloat64(*o.Lat)
	}
	if latQ != "" {
		qs.Set("lat", latQ)
	}

	var lonQ string
	if o.Lon != nil {
		lonQ = swag.FormatFloat64(*o.Lon)
	}
	if lonQ != "" {
		qs.Set("lon", lonQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetCitiesURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetCitiesURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetCitiesURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetCitiesURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetCitiesURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetCitiesURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
