// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "title": "Pay Test API",
    "version": "0.1.0"
  },
  "basePath": "/v1",
  "paths": {
    "/cities": {
      "get": {
        "description": "Show a list of all cities",
        "produces": [
          "application/json"
        ],
        "tags": [
          "City"
        ],
        "summary": "Show a list of all cities",
        "responses": {
          "200": {
            "description": "Return an array with all cities",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/City"
              }
            }
          }
        }
      }
    },
    "/cities/{id}": {
      "get": {
        "description": "Show a single city by id",
        "produces": [
          "application/json"
        ],
        "tags": [
          "City"
        ],
        "summary": "Show a single city by id",
        "parameters": [
          {
            "type": "integer",
            "description": "The id of the city",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Return a single object with city data",
            "schema": {
              "$ref": "#/definitions/City"
            }
          },
          "404": {
            "description": "City not found"
          }
        }
      }
    },
    "/cities/{id}/weathers": {
      "get": {
        "description": "Show a list of weathers of a single city",
        "produces": [
          "application/json"
        ],
        "tags": [
          "Weather"
        ],
        "summary": "Show a list of weathers of a single city",
        "parameters": [
          {
            "type": "integer",
            "description": "The id of the city",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Return an array of weathers of a single city",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/WeatherData"
              }
            }
          },
          "404": {
            "description": "City not found"
          }
        }
      }
    }
  },
  "definitions": {
    "City": {
      "type": "object",
      "properties": {
        "coord": {
          "$ref": "#/definitions/CityCoord"
        },
        "country": {
          "description": "Initials of country",
          "type": "string",
          "example": "AR"
        },
        "geoname": {
          "$ref": "#/definitions/CityGeoName"
        },
        "id": {
          "description": "Id of the city",
          "type": "integer",
          "example": 1
        },
        "name": {
          "description": "Name of city",
          "type": "string",
          "example": "Campeche"
        },
        "stat": {
          "$ref": "#/definitions/CityStat"
        },
        "stations": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CityStation"
          }
        },
        "zoom": {
          "description": "Zoom of city",
          "type": "number",
          "example": 7
        }
      }
    },
    "CityCoord": {
      "type": "object",
      "required": [
        "lat",
        "lon"
      ],
      "properties": {
        "lat": {
          "description": "Latitude of the city",
          "type": "number",
          "example": 154.124546
        },
        "lon": {
          "description": "Longitude of the city",
          "type": "number",
          "example": -2354.132455
        }
      }
    },
    "CityGeoName": {
      "type": "object",
      "required": [
        "cl",
        "code",
        "parent"
      ],
      "properties": {
        "cl": {
          "description": "CL of city",
          "type": "string",
          "example": "P"
        },
        "code": {
          "description": "Code of city",
          "type": "string",
          "example": "PPLA"
        },
        "parent": {
          "description": "Parent of city",
          "type": "number",
          "example": 6546498
        }
      }
    },
    "CityStat": {
      "type": "object",
      "required": [
        "level",
        "population"
      ],
      "properties": {
        "level": {
          "description": "Level of the city",
          "type": "number",
          "example": 1
        },
        "population": {
          "description": "Population of city",
          "type": "number",
          "example": 205212
        }
      }
    },
    "CityStation": {
      "type": "object",
      "required": [
        "id",
        "dist",
        "kf"
      ],
      "properties": {
        "dist": {
          "description": "Dist of city station",
          "type": "number",
          "example": 4
        },
        "id": {
          "description": "Id of city station",
          "type": "number",
          "example": 3985
        },
        "kf": {
          "description": "Kf of city station",
          "type": "number",
          "example": 1
        }
      }
    },
    "Weather": {
      "type": "object",
      "properties": {
        "cityId": {
          "description": "Id of the city",
          "type": "integer",
          "example": 1
        },
        "data": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/WeatherData"
          }
        }
      }
    },
    "WeatherData": {
      "type": "object",
      "properties": {
        "clouds": {
          "description": "Clouds of weather",
          "type": "number",
          "example": 76
        },
        "deg": {
          "description": "Deg of weather",
          "type": "number",
          "example": 28
        },
        "dt": {
          "description": "Date of weather",
          "type": "number",
          "example": 1489428000
        },
        "humidity": {
          "description": "Humidity of weather",
          "type": "number",
          "example": 67
        },
        "pressure": {
          "description": "Pressure of weather",
          "type": "number",
          "example": 997.85
        },
        "speed": {
          "description": "Speed of weather",
          "type": "number",
          "example": 2.96
        },
        "temp": {
          "$ref": "#/definitions/WeatherTemp"
        },
        "uvi": {
          "description": "UVI of weather",
          "type": "number",
          "example": 7.59
        },
        "weather": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/WeatherInfo"
          }
        }
      }
    },
    "WeatherInfo": {
      "type": "object",
      "properties": {
        "description": {
          "description": "description of weather info",
          "type": "string",
          "example": "broken clouds"
        },
        "icon": {
          "description": "Icon of weather info",
          "type": "string",
          "example": "04n"
        },
        "id": {
          "description": "Id of weather info",
          "type": "number",
          "example": 803
        },
        "main": {
          "description": "Main of weather info",
          "type": "string",
          "example": "clouds"
        }
      }
    },
    "WeatherTemp": {
      "type": "object",
      "properties": {
        "day": {
          "description": "Day of weather temp",
          "type": "number",
          "example": 288.64
        },
        "eve": {
          "description": "Eve of weather temp",
          "type": "number",
          "example": 288.64
        },
        "max": {
          "description": "Max of weather temp",
          "type": "number",
          "example": 288.64
        },
        "min": {
          "description": "Min of weather temp",
          "type": "number",
          "example": 288.64
        },
        "morn": {
          "description": "Morn of weather temp",
          "type": "number",
          "example": 288.64
        },
        "night": {
          "description": "Night of weather temp",
          "type": "number",
          "example": 288.64
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "title": "Pay Test API",
    "version": "0.1.0"
  },
  "basePath": "/v1",
  "paths": {
    "/cities": {
      "get": {
        "description": "Show a list of all cities",
        "produces": [
          "application/json"
        ],
        "tags": [
          "City"
        ],
        "summary": "Show a list of all cities",
        "responses": {
          "200": {
            "description": "Return an array with all cities",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/City"
              }
            }
          }
        }
      }
    },
    "/cities/{id}": {
      "get": {
        "description": "Show a single city by id",
        "produces": [
          "application/json"
        ],
        "tags": [
          "City"
        ],
        "summary": "Show a single city by id",
        "parameters": [
          {
            "type": "integer",
            "description": "The id of the city",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Return a single object with city data",
            "schema": {
              "$ref": "#/definitions/City"
            }
          },
          "404": {
            "description": "City not found"
          }
        }
      }
    },
    "/cities/{id}/weathers": {
      "get": {
        "description": "Show a list of weathers of a single city",
        "produces": [
          "application/json"
        ],
        "tags": [
          "Weather"
        ],
        "summary": "Show a list of weathers of a single city",
        "parameters": [
          {
            "type": "integer",
            "description": "The id of the city",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Return an array of weathers of a single city",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/WeatherData"
              }
            }
          },
          "404": {
            "description": "City not found"
          }
        }
      }
    }
  },
  "definitions": {
    "City": {
      "type": "object",
      "properties": {
        "coord": {
          "$ref": "#/definitions/CityCoord"
        },
        "country": {
          "description": "Initials of country",
          "type": "string",
          "example": "AR"
        },
        "geoname": {
          "$ref": "#/definitions/CityGeoName"
        },
        "id": {
          "description": "Id of the city",
          "type": "integer",
          "example": 1
        },
        "name": {
          "description": "Name of city",
          "type": "string",
          "example": "Campeche"
        },
        "stat": {
          "$ref": "#/definitions/CityStat"
        },
        "stations": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CityStation"
          }
        },
        "zoom": {
          "description": "Zoom of city",
          "type": "number",
          "example": 7
        }
      }
    },
    "CityCoord": {
      "type": "object",
      "required": [
        "lat",
        "lon"
      ],
      "properties": {
        "lat": {
          "description": "Latitude of the city",
          "type": "number",
          "example": 154.124546
        },
        "lon": {
          "description": "Longitude of the city",
          "type": "number",
          "example": -2354.132455
        }
      }
    },
    "CityGeoName": {
      "type": "object",
      "required": [
        "cl",
        "code",
        "parent"
      ],
      "properties": {
        "cl": {
          "description": "CL of city",
          "type": "string",
          "example": "P"
        },
        "code": {
          "description": "Code of city",
          "type": "string",
          "example": "PPLA"
        },
        "parent": {
          "description": "Parent of city",
          "type": "number",
          "example": 6546498
        }
      }
    },
    "CityStat": {
      "type": "object",
      "required": [
        "level",
        "population"
      ],
      "properties": {
        "level": {
          "description": "Level of the city",
          "type": "number",
          "example": 1
        },
        "population": {
          "description": "Population of city",
          "type": "number",
          "example": 205212
        }
      }
    },
    "CityStation": {
      "type": "object",
      "required": [
        "id",
        "dist",
        "kf"
      ],
      "properties": {
        "dist": {
          "description": "Dist of city station",
          "type": "number",
          "example": 4
        },
        "id": {
          "description": "Id of city station",
          "type": "number",
          "example": 3985
        },
        "kf": {
          "description": "Kf of city station",
          "type": "number",
          "example": 1
        }
      }
    },
    "Weather": {
      "type": "object",
      "properties": {
        "cityId": {
          "description": "Id of the city",
          "type": "integer",
          "example": 1
        },
        "data": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/WeatherData"
          }
        }
      }
    },
    "WeatherData": {
      "type": "object",
      "properties": {
        "clouds": {
          "description": "Clouds of weather",
          "type": "number",
          "example": 76
        },
        "deg": {
          "description": "Deg of weather",
          "type": "number",
          "example": 28
        },
        "dt": {
          "description": "Date of weather",
          "type": "number",
          "example": 1489428000
        },
        "humidity": {
          "description": "Humidity of weather",
          "type": "number",
          "example": 67
        },
        "pressure": {
          "description": "Pressure of weather",
          "type": "number",
          "example": 997.85
        },
        "speed": {
          "description": "Speed of weather",
          "type": "number",
          "example": 2.96
        },
        "temp": {
          "$ref": "#/definitions/WeatherTemp"
        },
        "uvi": {
          "description": "UVI of weather",
          "type": "number",
          "example": 7.59
        },
        "weather": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/WeatherInfo"
          }
        }
      }
    },
    "WeatherInfo": {
      "type": "object",
      "properties": {
        "description": {
          "description": "description of weather info",
          "type": "string",
          "example": "broken clouds"
        },
        "icon": {
          "description": "Icon of weather info",
          "type": "string",
          "example": "04n"
        },
        "id": {
          "description": "Id of weather info",
          "type": "number",
          "example": 803
        },
        "main": {
          "description": "Main of weather info",
          "type": "string",
          "example": "clouds"
        }
      }
    },
    "WeatherTemp": {
      "type": "object",
      "properties": {
        "day": {
          "description": "Day of weather temp",
          "type": "number",
          "example": 288.64
        },
        "eve": {
          "description": "Eve of weather temp",
          "type": "number",
          "example": 288.64
        },
        "max": {
          "description": "Max of weather temp",
          "type": "number",
          "example": 288.64
        },
        "min": {
          "description": "Min of weather temp",
          "type": "number",
          "example": 288.64
        },
        "morn": {
          "description": "Morn of weather temp",
          "type": "number",
          "example": 288.64
        },
        "night": {
          "description": "Night of weather temp",
          "type": "number",
          "example": 288.64
        }
      }
    }
  }
}`))
}
