// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CityCoord city coord
// swagger:model CityCoord
type CityCoord struct {

	// Latitude of the city
	// Required: true
	Lat *float64 `json:"lat"`

	// Longitude of the city
	// Required: true
	Lon *float64 `json:"lon"`
}

// Validate validates this city coord
func (m *CityCoord) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLat(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLon(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CityCoord) validateLat(formats strfmt.Registry) error {

	if err := validate.Required("lat", "body", m.Lat); err != nil {
		return err
	}

	return nil
}

func (m *CityCoord) validateLon(formats strfmt.Registry) error {

	if err := validate.Required("lon", "body", m.Lon); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CityCoord) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CityCoord) UnmarshalBinary(b []byte) error {
	var res CityCoord
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
