// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CityStat city stat
// swagger:model CityStat
type CityStat struct {

	// Level of the city
	// Required: true
	Level *float64 `json:"level"`

	// Population of city
	// Required: true
	Population *float64 `json:"population"`
}

// Validate validates this city stat
func (m *CityStat) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLevel(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePopulation(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CityStat) validateLevel(formats strfmt.Registry) error {

	if err := validate.Required("level", "body", m.Level); err != nil {
		return err
	}

	return nil
}

func (m *CityStat) validatePopulation(formats strfmt.Registry) error {

	if err := validate.Required("population", "body", m.Population); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CityStat) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CityStat) UnmarshalBinary(b []byte) error {
	var res CityStat
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
