// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CityStation city station
// swagger:model CityStation
type CityStation struct {

	// Dist of city station
	// Required: true
	Dist *float64 `json:"dist"`

	// Id of city station
	// Required: true
	ID *float64 `json:"id"`

	// Kf of city station
	// Required: true
	Kf *float64 `json:"kf"`
}

// Validate validates this city station
func (m *CityStation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDist(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateKf(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CityStation) validateDist(formats strfmt.Registry) error {

	if err := validate.Required("dist", "body", m.Dist); err != nil {
		return err
	}

	return nil
}

func (m *CityStation) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *CityStation) validateKf(formats strfmt.Registry) error {

	if err := validate.Required("kf", "body", m.Kf); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CityStation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CityStation) UnmarshalBinary(b []byte) error {
	var res CityStation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
