// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// WeatherTemp weather temp
// swagger:model WeatherTemp
type WeatherTemp struct {

	// Day of weather temp
	Day float64 `json:"day,omitempty"`

	// Eve of weather temp
	Eve float64 `json:"eve,omitempty"`

	// Max of weather temp
	Max float64 `json:"max,omitempty"`

	// Min of weather temp
	Min float64 `json:"min,omitempty"`

	// Morn of weather temp
	Morn float64 `json:"morn,omitempty"`

	// Night of weather temp
	Night float64 `json:"night,omitempty"`
}

// Validate validates this weather temp
func (m *WeatherTemp) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WeatherTemp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WeatherTemp) UnmarshalBinary(b []byte) error {
	var res WeatherTemp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
