// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// WeatherInfo weather info
// swagger:model WeatherInfo
type WeatherInfo struct {

	// description of weather info
	Description string `json:"description,omitempty"`

	// Icon of weather info
	Icon string `json:"icon,omitempty"`

	// Id of weather info
	ID float64 `json:"id,omitempty"`

	// Main of weather info
	Main string `json:"main,omitempty"`
}

// Validate validates this weather info
func (m *WeatherInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WeatherInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WeatherInfo) UnmarshalBinary(b []byte) error {
	var res WeatherInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
